---
title: "Transpop"
output: html_notebook
---




```{r}
library(partykit)
library(tidyverse)
```

```{r}
transpop <- read.delim("37938-0005-Data.tsv")
```


```{r}
transonly <- transpop |>
  filter(GENDER_IDENTITY > 2) |>
  mutate(GENDER_IDENTITY = as.factor(GENDER_IDENTITY)) |>
  select(
    STUDYID,
    WEIGHT_TRANSPOP,
    #demographics
    GENDER_IDENTITY,
    RACE_RECODE_CAT5,
    SEXMINID,
    AGE,
    #trans-specific variables
    INTERNALIZED_I,
    EVERYDAY_I,
    CHILDGNC_I,
    NONDISCLOSURE_I,
    NEGEXPFUTURE_I,
    SOCSUPPORT_I,
    CONNECTEDNESS_I,
    NONAFFIRM_I,
    HCTHREAT_I,
    #positive health outcomes
    LIFESAT,
    SOCIALWB
  )
```


```{r echo=F,message=F,output=F}
# Life satisfaction - demographics only
lifesat_tree1 = ctree(
  formula = as.ordered(LIFESAT) ~ AGE + GENDER_IDENTITY + RACE_RECODE_CAT5 +
    SEXMINID,
  data = transonly,
  minbucket = 26,
  multiway = T,
  na.action = na.omit,
  weights = WEIGHT_TRANSPOP
)

# Social wellbeing - demographics only
socialwb_tree1 = ctree(
  formula = as.ordered(SOCIALWB) ~ AGE + GENDER_IDENTITY + RACE_RECODE_CAT5 +
    SEXMINID,
  data = transonly,
  minbucket = 26,
  multiway = T,
  na.action = na.omit,
  weights = WEIGHT_TRANSPOP
)

# Life satisfaction - stressors only
lifesat_tree_stressors = ctree(
  formula = as.ordered(LIFESAT) ~ INTERNALIZED_I +
    EVERYDAY_I + CHILDGNC_I + NONDISCLOSURE_I +
    NEGEXPFUTURE_I + SOCSUPPORT_I + CONNECTEDNESS_I +
    NONAFFIRM_I + HCTHREAT_I + SEXMINID,
  data = transonly,
  minbucket = 26,
  multiway = T,
  na.action = na.omit,
  weights = WEIGHT_TRANSPOP
)

# social wellbeing - stressors only
socialwb_tree_stressors = ctree(
  formula = as.ordered(SOCIALWB) ~ INTERNALIZED_I +
    EVERYDAY_I + CHILDGNC_I + NONDISCLOSURE_I +
    NEGEXPFUTURE_I + SOCSUPPORT_I + CONNECTEDNESS_I +
    NONAFFIRM_I + HCTHREAT_I + SEXMINID,
  data = transonly,
  minbucket = 26,
  multiway = T,
  na.action = na.omit,
  weights = WEIGHT_TRANSPOP
)

```

```{r}
lifesat_tree1
plot(lifesat_tree1)
```

```{r}
socialwb_tree1
plot(socialwb_tree1)
```

```{r}
lifesat_tree_stressors
plot(lifesat_tree_stressors)
```

```{r}
socialwb_tree_stressors
plot(socialwb_tree_stressors)
```

Meyer, I. H. (2021). TransPop, United States, 2016-2018 [Dataset]. Inter-university Consortium for Political and Social Research [distributor]. https://doi.org/10.3886/ICPSR37938.v1

